Repository DiyorMarket/CheckDrive.Api, pull requests merged in 2024-05, with the labels that each got.

#15 Create repositories interfaces
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/CheckDriveDbContext.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Configurations/TechnicianEntityConfiguration.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/Account.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/DispetcherReview.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/Technician.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IAccountRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/ICarRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IDispatcherRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IDispatcherReviewRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IDoctorRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IDoctorReviewRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IDriverRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IMechanicAcceptenceRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IMechanicHandoverRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IMechanicRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IOperatorRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IOperatorReviewRepository.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IRepositoryBase.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IRoleRepository.cs
Labels: duplicate, enhancement

#16 Add EntityBase to Entities
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Configurations/AccountEntityConfiguration.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Configurations/CarEntityConfiguration.cs
  CheckDrive.Api/CheckDriver.Domain/Common/EntityBase.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/Account.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/Car.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/Dispatcher.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/DispatcherReview.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/Doctor.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/DoctorReview.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/Driver.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/Mechanic.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/MechanicAcceptance.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/MechanicHandover.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/Operator.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/OperatorReview.cs
  CheckDrive.Api/CheckDriver.Domain/Entities/Role.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Repositories/IRepositoryBase.cs
Labels: duplicate

#18 Add Repositories and rename libraries name
  CheckDrive.Api/CheckDricer.Infrastructure/CheckDrive.Infrastructure.csproj
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/AccountRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/CarRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/DispatcherRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/DispatcherReviewRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/DoctorRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/DoctorReviewRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/DriverRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/MechanicAcceptenceRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/MechanicHandoverRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/MechanicRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/OperatorRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/OperatorReviewRepository.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/RepositoryBase.cs
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Repositories/RoleRepository.cs
  CheckDrive.Api/CheckDrive.Api.sln
  CheckDrive.Api/CheckDrive.Api/CheckDrive.Api.csproj
  CheckDrive.Api/CheckDriver.Domain/CheckDrive.Domain.csproj
  CheckDrive.Api/CheckDriver.Services/CheckDrive.Services.csproj
Labels: duplicate, enhancement, invalid

#24 Create DTOs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Account/AccountDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Account/AccountForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Account/AccountForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Car/CarDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Car/CarForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Car/CarForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Dispatcher/DispatcherDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Dispatcher/DispatcherForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Dispatcher/DispatcherForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/DispatcherReview/DispatcherReviewDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/DispatcherReview/DispatcherReviewForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/DispatcherReview/DispatcherReviewForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Doctor/DoctorDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Doctor/DoctorForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Doctor/DoctorForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/DoctorReview/DoctorReviewDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/DoctorReview/DoctorReviewForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/DoctorReview/DoctorReviewForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Driver/DriverDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Driver/DriverForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Driver/DriverForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Mechanic/MechanicDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Mechanic/MechanicForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Mechanic/MechanicForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/MechanicAcceptance/MechanicAcceptanceDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/MechanicAcceptance/MechanicAcceptanceForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/MechanicAcceptance/MechanicAcceptanceForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/MechanicHandover/MechanicHandoverDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/MechanicHandover/MechanicHandoverForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/MechanicHandover/MechanicHandoverForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Operator/OperatorDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Operator/OperatorForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Operator/OperatorForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/OperatorReview/OperatorReviewDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/OperatorReview/OperatorReviewForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/OperatorReview/OperatorReviewForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Role/RoleDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Role/RoleForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Role/RoleForUpdateDto.cs
Labels: enhancement

#28 Create services' interfaces
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IAccountService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/ICarService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IDispatcherReviewService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IDispatcherService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IDoctorReviewService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IDoctorService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IDriverService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IMechanicAcceptenceService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IMechanicHandoverService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IMechanicService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IOperatorReviewService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IOperatorService.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IRoleService.cs
Labels: enhancement

#30 Create Logger
  CheckDrive.Api/CheckDricer.Infrastructure/CheckDrive.Infrastructure.csproj
  CheckDrive.Api/CheckDrive.Api/CheckDrive.Api.csproj
  CheckDrive.Api/CheckDrive.Api/Extensions/ConfigureServicesExtensions.cs
  CheckDrive.Api/CheckDrive.Api/Program.cs
  CheckDrive.Api/CheckDriver.Domain/CheckDrive.Domain.csproj
  CheckDrive.Api/CheckDriver.Services/CheckDrive.Services.csproj
Labels: enhancement

#32 Create Middleware
  CheckDrive.Api/CheckDrive.Api/Middlewares/ErrorHandlerMiddleware.cs
  CheckDrive.Api/CheckDrive.Api/Program.cs
Labels: enhancement

#34 Add Pagination and use
  CheckDrive.Api/CheckDriver.Domain/Pagniation/PaginatedList.cs
  CheckDrive.Api/CheckDriver.Domain/Pagniation/PaginationExtension.cs
Labels: enhancement

#38 Create Account Controller and Service
  CheckDrive.Api/CheckDricer.Infrastructure/Persistence/Migrations/CheckDriveDbContextModelSnapshot.cs
  CheckDrive.Api/CheckDrive.Api/CheckDrive.Api.csproj
  CheckDrive.Api/CheckDrive.Api/Controllers/AccountController.cs
  CheckDrive.Api/CheckDrive.Api/Controllers/WeatherForecastController.cs
  CheckDrive.Api/CheckDrive.Api/Extensions/ConfigureServicesExtensions.cs
  CheckDrive.Api/CheckDrive.Api/Program.cs
  CheckDrive.Api/CheckDrive.Api/appsettings.json
  CheckDrive.Api/CheckDriver.Domain/DTOs/Account/AccountDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Account/AccountForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Account/AccountForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IAccountService.cs
  CheckDrive.Api/CheckDriver.Domain/Pagniation/PaginatedList.cs
  CheckDrive.Api/CheckDriver.Services/AccountService.cs
  CheckDrive.Api/CheckDriver.Services/CheckDrive.Services.csproj
  CheckDrive.Api/CheckDriver.Services/Class1.cs
Labels: enhancement

#42 Create car controller and service
  CheckDrive.Api/CheckDrive.Api/Controllers/AccountController.cs
  CheckDrive.Api/CheckDrive.Api/Controllers/AccountsController.cs
  CheckDrive.Api/CheckDrive.Api/Controllers/CarController.cs
  CheckDrive.Api/CheckDrive.Api/Extensions/ConfigureServicesExtensions.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/Car/CarForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/ICarService.cs
  CheckDrive.Api/CheckDriver.Services/AccountService.cs
  CheckDrive.Api/CheckDriver.Services/CarService.cs
Labels: enhancement

#49 Create DoctorReview Controller and Service
  CheckDrive.Api/CheckDrive.Api/Controllers/DoctorReviewController.cs
  CheckDrive.Api/CheckDrive.Api/Extensions/ConfigureServicesExtensions.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/DoctorReview/DoctorReviewForCreateDto.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/DoctorReview/DoctorReviewForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IDoctorReviewService.cs
  CheckDrive.Api/CheckDriver.Services/DispatcherReviewService.cs
  CheckDrive.Api/CheckDriver.Services/DoctorReviewService.cs
Labels: duplicate, enhancement

#63 Create OperatorReview Controller and Service
  CheckDrive.Api/CheckDrive.Api/Controllers/OperatorReviewController.cs
  CheckDrive.Api/CheckDrive.Api/Extensions/ConfigureServicesExtensions.cs
  CheckDrive.Api/CheckDriver.Domain/DTOs/OperatorReview/OperatorReviewForUpdateDto.cs
  CheckDrive.Api/CheckDriver.Domain/Interfaces/Services/IOperatorReviewService.cs
  CheckDrive.Api/CheckDriver.Services/OperatorReviewService.cs
Labels: enhancement

#67 Deployed CheckDrive.DTOs NuGet Package
  CheckDrive.Api/CheckDrive.DTOs/Account/AccountDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Account/AccountForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Account/AccountForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Car/CarDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Car/CarForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Car/CarForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/CheckDrive.DTOs.csproj
  CheckDrive.Api/CheckDrive.DTOs/Dispatcher/DispatcherDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Dispatcher/DispatcherForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Dispatcher/DispatcherForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/DispatcherReview/DispatcherReviewDto.cs
  CheckDrive.Api/CheckDrive.DTOs/DispatcherReview/DispatcherReviewForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/DispatcherReview/DispatcherReviewForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Doctor/DoctorDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Doctor/DoctorForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Doctor/DoctorForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/DoctorReview/DoctorReviewDto.cs
  CheckDrive.Api/CheckDrive.DTOs/DoctorReview/DoctorReviewForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/DoctorReview/DoctorReviewForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Driver/DriverDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Driver/DriverForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Driver/DriverForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Mechanic/MechanicDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Mechanic/MechanicForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Mechanic/MechanicForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/MechanicAcceptance/MechanicAcceptanceDto.cs
  CheckDrive.Api/CheckDrive.DTOs/MechanicAcceptance/MechanicAcceptanceForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/MechanicAcceptance/MechanicAcceptanceForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/MechanicHandover/MechanicHandoverDto.cs
  CheckDrive.Api/CheckDrive.DTOs/MechanicHandover/MechanicHandoverForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/MechanicHandover/MechanicHandoverForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Operator/OperatorDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Operator/OperatorForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Operator/OperatorForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/OperatorReview/OperatorReviewDto.cs
  CheckDrive.Api/CheckDrive.DTOs/OperatorReview/OperatorReviewForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/OperatorReview/OperatorReviewForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Role/RoleDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Role/RoleForCreateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Role/RoleForUpdateDto.cs
  CheckDrive.Api/CheckDrive.DTOs/Status.cs
  CheckDrive.Api/CheckDrive.DTOs/StatusForDto.cs
Labels: enhancement

#79 Add Doctor Properti
  CheckDrive.Api/CheckDrive.ApiContracts/DoctorReview/DoctorReviewDto.cs
Labels: enhancement

#80 Upgrade all services mappings
  CheckDrive.Api/CheckDrive.Api/CheckDrive.Api.csproj
  CheckDrive.Api/CheckDrive.Api/appsettings.json
  CheckDrive.Api/CheckDrive.Domain/CheckDrive.Domain.csproj
  CheckDrive.Api/CheckDrive.Domain/Mappings/DispatcherReviewMappings.cs
  CheckDrive.Api/CheckDrive.Domain/Mappings/DoctorReviewMappings.cs
  CheckDrive.Api/CheckDrive.Domain/Mappings/MechanicAcceptanceMappings.cs
  CheckDrive.Api/CheckDrive.Domain/Mappings/MechanicHandoverMappings.cs
  CheckDrive.Api/CheckDrive.Domain/Mappings/OperatorReviewMappings.cs
  CheckDrive.Api/CheckDrive.Infrastructure/CheckDrive.Infrastructure.csproj
  CheckDrive.Api/CheckDrive.Services/CheckDrive.Services.csproj
  CheckDrive.Api/CheckDrive.Services/DispatcherReviewService.cs
  CheckDrive.Api/CheckDrive.Services/DoctorReviewService.cs
  CheckDrive.Api/CheckDrive.Services/MechanicAcceptanceService.cs
  CheckDrive.Api/CheckDrive.Services/MechanicHandoverService.cs
  CheckDrive.Api/CheckDrive.Services/OperatorReviewService.cs
Labels: help wanted

#87 Add Authorization and Authontication
  CheckDrive.Api/CheckDrive.Api/Controllers/AccountsController.cs
  CheckDrive.Api/CheckDrive.Api/Controllers/AuthorizationController.cs
  CheckDrive.Api/CheckDrive.Api/Controllers/CarsController.cs
  CheckDrive.Api/CheckDrive.Api/Controllers/DispatchersController.cs
  CheckDrive.Api/CheckDrive.Api/Controllers/DoctorsController.cs
  CheckDrive.Api/CheckDrive.Api/Controllers/DriversController.cs
  CheckDrive.Api/CheckDrive.Api/Controllers/MechanicsController.cs
  CheckDrive.Api/CheckDrive.Api/Controllers/OperatorsController.cs
  CheckDrive.Api/CheckDrive.Api/Controllers/RolesController.cs
  CheckDrive.Api/CheckDrive.Api/Extensions/ConfigureServicesExtensions.cs
  CheckDrive.Api/CheckDrive.Api/Program.cs
  CheckDrive.Api/CheckDrive.Api/appsettings.json
  CheckDrive.Api/CheckDrive.Domain/Interfaces/Auth/IJwtProvider.cs
  CheckDrive.Api/CheckDrive.Domain/Interfaces/Auth/IPasswordHasher.cs
  CheckDrive.Api/CheckDrive.Domain/Interfaces/Services/IAuthorizationService.cs
  CheckDrive.Api/CheckDrive.Infrastructure/CheckDrive.Infrastructure.csproj
  CheckDrive.Api/CheckDrive.Infrastructure/JwtToken/JwtOptions.cs
  CheckDrive.Api/CheckDrive.Infrastructure/JwtToken/JwtProvider.cs
  CheckDrive.Api/CheckDrive.Infrastructure/PasswordHash/PasswordHasher.cs
  CheckDrive.Api/CheckDrive.Services/AccountService.cs
  CheckDrive.Api/CheckDrive.Services/AuthorizationService.cs
Labels: Task
